project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls',namespace="users")),
]

users/urls.py
from django.urls import path

from users.views import signup,userlogout,userlogin,home

app_name = 'users'
urlpatterns = [
    path('',home,name="home"),
    path('signup/',signup,name="signup"),
    path('logout/',userlogout,name="userlogout"),
    path('login/',userlogin,name="userlogin"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("email",)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout,authenticate,login
from django.contrib.auth.forms import AuthenticationForm

from users.forms import CustomUserCreationForm

def home(request):
    return render(request,'home.html')

def userlogin(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)
        if user:
            login(request,user)
            return redirect('users:home')
    context = {'form':form}
    return render(request,'login.html',context)

def signup(request):
    form = CustomUserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {'form':form}
    return render(request,'signup.html',context)

def userlogout(request):
    logout(request)
    return render(request,'signup.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>playground</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock navbar %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:userlogin' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if not request.user.is_authenticated %}disabled{% endif %}" href="{% url 'users:userlogout' %}">Logout</a>
        </li>
      </ul>
</nav>

users/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h3>welcome {{request.user}}</h3>
<p>this is home page</p>
{% endblock content %}

users/templates/login.html
{% extends 'base.html' %}
{% block content %}
<p>this is login page</p>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock content %}

users/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<form method='POST' action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>
{% endblock content %}